myPolls/myPolls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
]

myPolls/polls/urls.py
from django.urls import path
from . import views


app_name = "polls"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.details, name='details'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

myPolls/polls/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.TextField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

myPolls/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from .models import Question, Choice

# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    
    context = {'latest_question_list' : latest_question_list}
    return render(request, 'polls/index.html', context)

def details(request, question_id):
    return HttpResponse('this is the question with id: %s' % question_id )

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html',{'question':question,'error_message':'you didn\'t select a choice'})

    else:
        selected_choice.vote += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

myPolls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p>
    <srong>{{ error_message }}</srong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %} {% for choice in question.choice_set.all %}
    <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label> {% endfor %}<input type="submit" value="vote">
</form>

myPolls/templates/polls/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>

{% endif %}

myPolls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>
        <h1>{{ choice.choice_text}} with total of : {{ choice.vote }} votes</h1>
    </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:vote' question.id %}">vote again?</a>